avajs/eslint-plugin-ava

- docs/rules/no-skip-test.md
- index.js
- readme.md
- rules/no-skip-test.js
- test/no-skip-test.js
Adds no-skip-test rule (fixes #3)
Let me know if I need to change anything ;)
One this gets merged, I'll submit the PRs for all, or most of, the rules I originally submitted in #11.
> add no-skip-test rule (fixes #3)

- docs/rules/test-title.md
- index.js
- readme.md
- rules/test-title.js
- test/test-title.js
Adds test-title rule (fixes #8)
Let me know if I need to change anything ;)
> add test-title rule (fixes #8)

- docs/rules/no-identical-title.md
- index.js
- readme.md
- rules/no-identical-title.js
- test/no-identical-title.js
Adds no-identical-title rule (fixes #7)
Let me know if I need to change anything ;)
> add no-identical-title rule (fixes #7)

- docs/rules/no-cb-test.md
- index.js
- readme.md
- rules/no-cb-test.js
- test/no-cb-test.js
Adds no-cb-test rule (fixes #2) :)
cc @sindresorhus @twada (@twada let us know if you want us to stop pinging you ;) )
> add no-cb-test rule (fixes #2)

- docs/rules/no-skip-assert.md
- index.js
- readme.md
- rules/no-skip-assert.js
- test/no-skip-assert.js
- util.js
add no-skip-assert rule (fixes #16) :)
> add no-skip-assert rule (fixes #16)

- docs/rules/no-only-test.md
- index.js
- readme.md
- rules/no-only-test.js
- test/no-only-test.js
add no-only-test-rule (fixes #5) :)
> add no-only-test-rule (fixes #5)

- docs/rules/use-test.md
- index.js
- readme.md
- rules/use-test.js
- test/use-test.js
adds `use-test` rule (fixes #39) :)
> add `use-test` rule (fixes #39)

- docs/rules/use-t.md
- index.js
- readme.md
- rules/use-t.js
- test/use-t.js
adds `use-t` rule (fixes #38) :)
> add `use-t` rule (fixes #38)

- test/max-asserts.js
- test/no-cb-test.js
- test/no-only-test.js
- test/no-skip-assert.js
- test/no-skip-test.js
- test/no-statement-after-end.js
- test/no-todo-test.js
- test/test-title.js
Simplify tests by using arrow functions
> Simplify tests by using arrow functions

- rules/max-asserts.js
- test/max-asserts.js
Limits max-asserts errors to 1 per test (fixes #45)
> Limit max-asserts errors to 1 per test (fixes #45)

- create-ava-rule.js
- rules/no-identical-title.js
- rules/test-title.js
- test/no-identical-title.js
- test/test-title.js
Do not enforce a title on hooks (fixes #52)
> Do not enforce a title on hooks (fixes #52)

- docs/rules/test-title.md
- rules/test-title.js
- test/test-title.js
Changes `test-title` default option (fixes #61)
Did a lof of changes to the tests (sorry...), but didn't update the tests cases themselves much.
> Change `test-title` default option (fixes #61)

- docs/rules/use-true-false.md
- index.js
- readme.md
- rules/use-true-false.js
- test/use-true-false.js
Adds `use-true` rule (fixes #77)
> Add `use-true-false` rule (fixes #77)

- docs/rules/assertion-arguments.md
- docs/rules/assertion-message.md
- docs/rules/max-asserts.md
- docs/rules/no-cb-test.md
- docs/rules/no-identical-title.md
- docs/rules/no-ignored-test-files.md
- docs/rules/no-invalid-end.md
- docs/rules/no-only-test.md
- docs/rules/no-skip-assert.md
- docs/rules/no-skip-test.md
- docs/rules/no-statement-after-end.md
- docs/rules/no-todo-test.md
- docs/rules/no-unknown-modifiers.md
- docs/rules/prefer-power-assert.md
- docs/rules/test-ended.md
- docs/rules/test-title.md
- docs/rules/use-t-well.md
- docs/rules/use-t.md
- docs/rules/use-test.md
- docs/rules/use-true-false.md
- readme.md
1. Move the project into an organization ✨
2. Link in french for	assertion-arguments.md
> Doc: Link french move the project into an organization

- docs/rules/prefer-power-assert.md
- rules/prefer-power-assert.js
- test/prefer-power-assert.js
> Update prefer-power-assert to accept falsy, true, false

- create-ava-rule.js
- package.json
- rules/assertion-arguments.js
- rules/assertion-message.js
- rules/max-asserts.js
- rules/no-cb-test.js
- rules/no-identical-title.js
- rules/no-ignored-test-files.js
- rules/no-invalid-end.js
- rules/no-only-test.js
- rules/no-skip-assert.js
- rules/no-skip-test.js
- rules/no-todo-test.js
- rules/no-unknown-modifiers.js
- rules/prefer-power-assert.js
- rules/test-ended.js
- rules/test-title.js
- rules/use-t-well.js
- rules/use-t.js
- rules/use-true-false.js
Replace custom methods by `enhance-visitors` methods.
Let me know what you think
> Replace custom methods by `enhance-visitors` methods

- docs/rules/no-todo-implementation.md
- index.js
- readme.md
- rules/no-todo-implementation.js
- test/no-todo-implementation.js
- util.js
Add `no-todo-implementation` rule (fixes #64)
> Add `no-todo-implementation` rule (fixes #64)

- docs/rules/prefer-async-await.md
- index.js
- readme.md
- rules/prefer-async-await.js
- test/prefer-async-await.js
Add `prefer-async-await` rule (fixes #123)
> Add `prefer-async-await` rule (fixes #123)

- create-ava-rule.js
- docs/rules/no-nested-tests.md
- index.js
- readme.md
- rules/no-nested-tests.js
- test/no-nested-tests.js
Add `no-nested-tests` rule (fixes #131)
> Add `no-nested-tests` rule (fixes #131)

- docs/rules/max-asserts.md
- docs/rules/no-duplicate-modifiers.md
- docs/rules/no-unknown-modifiers.md
- index.js
- readme.md
- rules/no-duplicate-modifiers.js
- rules/no-unknown-modifiers.js
- test/no-duplicate-modifiers.js
- util.js
Add `no-duplicate-modifiers` rule (fixes #137)
> Add `no-duplicate-modifiers` rule (fixes #137)

- docs/rules/no-async-fn-without-await.md
- index.js
- package.json
- readme.md
- rules/no-async-fn-without-await.js
- test/no-async-fn-without-await.js
Add `no-async-fn-without-await` rule (fixes #132)
> Add `no-async-fn-without-await` rule (fixes #132)

- rules/assertion-message.js
- rules/max-asserts.js
- rules/use-t-well.js
- test/max-asserts.js
- util.js
Do not count context methods as assertion methods (fixes #142)
> Do not count context methods as assertion methods (fixes #142)

- index.js
Works around [buggy `import-modules` directory resolution in Atom](https://github.com/sindresorhus/atom-linter-xo/issues/74#issuecomment-309194910).
Fixes sindresorhus/atom-linter-xo#74
> Make sure the rules directory is resolved correctly

- docs/rules/no-import-test-files.md
> Add support for `ava.config.js` in no-import-test-files.md

- rules/no-async-fn-without-await.js
- test/no-async-fn-without-await.js
> Fix async function with for-await-of loop being reported

- docs/rules/prefer-power-assert.md
- rules/prefer-power-assert.js
- test/prefer-power-assert.js
- test/use-t-well.js
- util.js
PR for #218. I added `t.assert()` to util and added a test case to use-t-well. Moved `t.true()` from allowed to not allowed in prefer-power-assert and added `t.assert()` to allowed methods. Also tried to update docs.
> Power assert rules

- docs/rules/no-ignored-test-files.md
- docs/rules/no-import-test-files.md
- docs/rules/no-todo-implementation.md
- docs/rules/no-unknown-modifiers.md
Fixes that some of the links in the documentation are not up to date.
> Fix some links

- docs/new-rule.md
The translation into French is done. Adding the link to the french doc
> Add link to french docs for `new-rule.md`

- docs/rules/prefer-t-regex.md
- docs/rules/test-title-format.md
News translations in french: 
* `prefer-t-regex.md`
* `test-title-format.md`
> Add link to french docs `prefer-t-regex.md` and `test-title-format.md`

- docs/rules/hooks-order.md
- index.js
- package.json
- readme.md
- rules/hooks-order.js
- test/hooks-order.js
> Add `hooks-order` rule

- docs/rules/hooks-order.md
- docs/rules/no-incorrect-deep-equal.md
- docs/rules/no-inline-assertions.md
* hooks-order.md
* no-incorrect-deep-equal.md
* no-inline-assertions.md
> Add three new links translated in french

- test/integration/test.js
I'm not fixing integration test.
We are updating the same script on `eslint-plugin-unicorn`, and I think this could help
https://github.com/sindresorhus/eslint-plugin-unicorn/pull/466
> Update integration test script

- test/integration/eslint-config-ava-tester/package-lock.json
- test/integration/eslint-config-ava-tester/package.json
> Fix integration test

- .travis.yml
> Update `.travis.yml`; don't test Node.js 6 & 8

- rules/assertion-arguments.js
- test/assertion-arguments.js
- test/use-t-well.js
- util.js
> Add `t.timeout` to `use-t-well` rule

- rules/assertion-arguments.js
- test/assertion-arguments.js
- test/use-t-well.js
- util.js
> Recognize t.try() assertion

- rules/assertion-arguments.js
- test/assertion-arguments.js
- test/use-t-well.js
- util.js
If you're adding a new rule, please follow [these steps](../docs/new-rule.md).
> Add t.teardown()
