avajs/eslint-plugin-ava

index.js
package.json
readme.md
test/prefer-power-assert.js

In the new recommended config I set up some defaults for environment and parser options. I noticed that you can also use `const ava = require('ava')` and not need `sourceType: module`. But all of the examples of AVA use the `import` syntax so I think this should be in the recommended configuration.
Feedback is definitely welcome.
Fixes #4
Fixes #17

Update to ESLint 2.0.0

---

docs/rules/max-asserts.md
index.js
readme.md
rules/max-asserts.js
test/max-asserts.js
util.js

add max-asserts rule (fixes #6) :)
Last one of the rules implemented in #11 :)

add max-asserts rule (fixes #6)

---

readme.md

Oops. Fix broken doc link for max-asserts.

Fix broken doc link for max-asserts

---

docs/rules/no-todo-test.md
index.js
readme.md
rules/no-todo-test.js
test/no-todo-test.js

Adds no-todo-test rule (fixes #31).
Let's wait until https://github.com/sindresorhus/ava/pull/565 lands before merging (or at least releasing) it, but we can already discuss the implementation (it's pretty much a no-skip-test copy and paste).

add no-todo-test rule (fixes #31)

---

index.js

This pull request is fixing:
```
1:1  error  Definition for rule 'no-identical-title' was not found                                    no-identical-title
1:1  error  Definition for rule 'no-invalid-end' was not found                                        no-invalid-end
1:1  error  Definition for rule 'no-only-test' was not found                                          no-only-test
1:1  error  Definition for rule 'no-skip-assert' was not found                                        no-skip-assert
1:1  error  Definition for rule 'no-skip-test' was not found                                          no-skip-test
1:1  error  Definition for rule 'test-ended' was not found                                            test-ended
1:1  error  Definition for rule 'test-title' was not found …
```

config: added ava prefix

---

rules/no-identical-title.js
test/no-identical-title.js

I noticed that the rule gets incorrectly triggered when using non-string literals (binary expressions, template literals...). Now I compare the nodes rather than the value of the title (which was undefined in the case of template literals for example...).
I also added a few tests of cases I could think of but that were already ok.
I can still see two edge cases for this rule, but I don't think we can really do much against (thought I should at least write them somewhere):
- Same title node used in different contexts (False error):
```js
let name = 'foo';
test(name, t => {
t.is(foo(), 1);
});
name = 'bar';
test(name, t => {
t.is(bar(), 1);
});
```
- Same expression value, but with different nodes (false pass):
```js
test("ab", t => { ... });
test("a"+"b", t => { ... });
```

Fix incorrect no-identical-rule errors for title expressions

---

rules/no-identical-title.js
rules/test-title.js
test/no-identical-title.js
test/test-title.js

Fixes a couple issues when using `test.todo()`:
* `test-title` incorrectly reports that the test doesn’t have a title when it does
* `no-identical-title` wasn’t pulling the right title, so if you had multiple `test.todo()`s in the file, it would error when it shouldn’t have

Fix errors with `test.todo()`

---

rules/no-identical-title.js
test/no-identical-title.js

Fixes #43.
The `no-indentical-rule` now tries to determine whether the title is dynamic (= contains a variable) or not, so that it doesn't flag titles like `\ ̀ ensure x=${expected} \ ̀`, but still flags titles like `\ ̀ ensure x=2 \ ̀` or `\ ̀ ensure x=${1 + 3}\ ̀` (template strings without any variables). Did the same thing for titles like "foo" + 1.
I feel like I'm forgetting cases, but it should fix #43 at least.
Note: also simplified the tests to use `t => {}` rather than `function() {}`

Fix `no-identical-title` for dynamic template strings

---

readme.md

Docs: Add missing rule  ̀no-stattement-after-end` in example rules configuration

Docs: Add missing rule in example rules configuration

---

rules/no-invalid-end.js

It's t.end(), no test.end(), isn't it?

Fix typo in no-invalid-end.js

---

rules/no-identical-title.js
rules/test-title.js

Fix incorrect exit visitors: we were using `Program.exit` in some places we should have been using `Program:exit`.

Fix incorrect exit visitors

---

docs/rules/max-asserts.md
docs/rules/test-title.md

Fix option configuration examples : prepend rules with "ava/".
FMI: Do you guys prefer to always add code via PRs, or can/should I push this kind of simple fix directly on master? There's no contribution guidelines for maintainers or anything, so I don't know what you agreed on.

Fix option configuration examples

---

index.js
readme.md

Changing all rule configurations from using 0/1/2 to using off/warn/error in rule configurations.
This would be consistent with ESLint's own [core config](https://github.com/eslint/eslint/blob/master/conf/eslint.json), and is easier to understood for beginners.

Use off/warn/error in rule configurations

---

docs/rules/prefer-power-assert.md
rules/prefer-power-assert.js
test/prefer-power-assert.js

Fixes #62
* rename `t.same()` to `t.deepEqual()`
* rename `t.notSame()` to `t.notDeepEqual()`
* rename `t.ok()` to `t.truthy()`
* rename `t.notOk()` to `t.falsy()`
* change bad link to "Enhanced assertion messages"
This is my first PR, be kind :smile:

Update the `prefer-power-assert` rule for AVA assert changes

---

docs/rules/test-ended.md
rules/test-ended.js
test/test-ended.js

fix(test-ended): false positive when passing `t.end` as a callback. Fixes #60.

---

docs/rules/max-asserts.md
docs/rules/no-ignored-test-files.md

Missed some `2` --> `"error"` changes, and in some examples, we used
```js
/*eslint max-asserts: [2, 5]*/
```
but it was missing the `ava/` prefix (--> `ava/max-asserts`)

Use "error" in rule docs, add missing ava/ prefix

---

docs/rules/assertion-message.md
index.js
readme.md
rules/assertion-message.js
test/assertion-message.js

Adds `assertion-message` rule (fixes #59)
Haven't added any middleground option between `always` and `never`, as I can't see any that makes sense at the moment.

Add `assertion-message` rule (fixes #59)

---

docs/rules/no-ignored-test-files.md
rules/no-ignored-test-files.js
test/no-ignored-test-files.js

https://github.com/sindresorhus/ava/pull/721

Support new test file conventions

---

docs/rules/use-t-well.md
index.js
readme.md
rules/use-t-well.js
test/use-t-well.js

Adds `use-t-well` rule
I originally wanted to make the rule `no-unknown-assertions`, but adding checks to member expressions (`t.context`, ...) was easy, so I've made the rule more global. It now handles quite a few cases. It looks fine to me now, but I wouldn't be surprised if I missed some edge cases (false positives mostly). (If you guys have a a few projects to test it on, that'd be nice)
Let me know what you think :)

Add `use-t-well` rule

---

rules/use-t-well.js
test/use-t-well.js

Allow `t.plan()` in the `use-t-well` rule

---

.travis.yml

Update Node.js version for Travis

Update Node.js version for Travis

---

rules/use-true-false.js
test/use-true-false.js

This fixes a crash in Atom using `linter-xo` that happens while typing on the opening bracket of `t.truthy(` or when closing on empty argument. This check makes sure the `arg` value is completely taken into account within the check before proceeding to check any of the `||` combinations. I was getting the crash in `eslint-plugin-ava` shipped with `xo@0.14` which has different code than the master here; but I think the fix is still valid here.

Properly check for valid argument Node in use-true-false rule

---

package.json
test/package.js

Add tests for checking the index file
I've been bitten a few times in another my lodash-fp plugin by the fact that my `index.js` file had some typos in it (either in the exported rule, or the recommended config).
I've thus added a test to verify those.

Add tests for checking the index file

---

rules/no-ignored-test-files.js
test/no-ignored-test-files.js

Handle linting from text in `no-ignored-test-files`. Fixes #91

Handle linting from text in `no-ignored-test-files`. Fixes #91

---

rules/use-t.js
test/use-t.js

`use-t` rule crashes with the snippet below, which obviously is not a proper test file but it's what the linter sees if you run it as you type (with eg. the `atom` plugin)
```js
import test from 'ava'
test()
```
I've fixed it and added a test for it.

fix use-t rule crashing when test() has no arguments

---

docs/rules/assertion-arguments.md
index.js
readme.md
rules/assertion-arguments.js
test/assertion-arguments.js
util.js

Add `assertion-arguments` rule (fixes #92)
Willing to change the name of the rule, but this is pretty generic, and maybe some day we'll want to detect the argument types. 
Probably to be followed by the deprecation of `assertion-message`.

Add `assertion-arguments` rule (fixes #92)

---

rules/no-unknown-modifiers.js
test/no-unknown-modifiers.js

With regards to the work being done in https://github.com/sindresorhus/ava/pull/806.
Since it looked like it will be merged soon, I've prepared the work here.

Support `always` modifier in `no-unknown-modifiers`

---

rules/no-identical-title.js
test/no-identical-title.js

Being `undefined`, I guess we can assume it's a anonymous title.

Allow multiple anonymous rules in `no-identical-title`

---

create-ava-rule.js
package.json
rules/assertion-arguments.js
rules/assertion-message.js
rules/max-asserts.js
rules/no-cb-test.js
rules/no-identical-title.js
rules/no-ignored-test-files.js
rules/no-invalid-end.js
rules/no-only-test.js
rules/no-skip-assert.js
rules/no-skip-test.js
rules/no-statement-after-end.js
rules/no-todo-test.js
rules/no-unknown-modifiers.js
rules/prefer-power-assert.js
rules/test-ended.js
rules/test-title.js
rules/use-t-well.js
rules/use-t.js
rules/use-true-false.js

Fixes #72
WIP, just tackled one of the rules, to see the reactions. Does this still look good to you @sindresorhus @jamestalmage @twada? If so, I'll go and do the others.

Simplifying tests

---

package.json
rules/no-ignored-test-files.js
test/no-ignored-test-files.js

AVA allows you to specify a single string for `files` in `package.json`. But that can cause a TypeError in certain situations, because we don't arrify it the way AVA does.

Arrify the files config.

---

rules/test-title.js
test/test-title.js

Currently, the `test-title` rule will freak out if you use macros with more than one argument.
Unfotuneately, this simple fix is going to let some errors slip through. Specifically, if you don't attach a `title` function to your macro, and don't supply a string title, we probably should error, but that requires some rather involved type analysis to see if they ever did attach a title method to the macro.

Allow macro use with `test-title` rule.

---

rules/no-unknown-modifiers.js
test/no-unknown-modifiers.js

add always, failing modifier. resolve #107

update no-unknown-modifier rules, resolve #107

---

package.json
rules/assertion-arguments.js
rules/assertion-message.js
rules/max-asserts.js
rules/no-cb-test.js
rules/no-identical-title.js
rules/no-ignored-test-files.js
rules/no-invalid-end.js
rules/no-only-test.js
rules/no-skip-assert.js
rules/no-skip-test.js
rules/no-statement-after-end.js
rules/no-todo-test.js
rules/no-unknown-modifiers.js
rules/prefer-power-assert.js
rules/test-ended.js
rules/test-title.js
rules/use-t-well.js
rules/use-t.js
rules/use-test.js
rules/use-true-false.js

Upgrade to Eslint 3 (fixes #128)
I didn't use the migration tool in the end as it adds spaces everywhere and destroys the indentation we had. It also indented the main rule function which was not needed.
I think that we could add a `recommended` setting and generate the recommended settings that way. Would remove a lot of boilerplate in addition to what has been done using `req-all`. I'll leave that for later.
Let me know if I've missed anything.

Upgrade to Eslint 3 (fixes #128)

---

docs/rules/use-t-well.md

The github diff is a bit unsuitable, hence:
```diff
- t.contxt.foo = 100; // Unknown member `context`
+ t.contxt.foo = 100; // Unknown member `contxt`
```

Fix tiny typo in use-t-well.md

---

rules/max-asserts.js
rules/no-async-fn-without-await.js
rules/no-identical-title.js
rules/no-ignored-test-files.js
rules/no-nested-tests.js
rules/no-statement-after-end.js
rules/test-ended.js
rules/test-title.js
rules/use-t.js
test/no-identical-title.js
test/no-ignored-test-files-with-package.js

Fix linting errors from XO 0.17

Fix linting errors from XO 0.17

---

package.json
rules/no-async-fn-without-await.js
test/no-async-fn-without-await.js

Fix no-async-fn-without-await when used with default parser (fixes #147)
Espree supports async/await, but it doesn't generate the same AST as babel-eslint when using async/await. Espree uses a `AwaitExpression` node (which makes ore sense IMO), while `babel-eslint` uses `YieldExpression` (which I think could give incorrect results when using the generator `yield` keyword).
The test file looks like it's been rewritten, but I just indented the whole test suite, to be able to use it with both parsers (I've added one test, and that's it).
The tests fail because of XO, I'll do that in another PR real quick.
EDIT: Done in #149. Tests for this PR should be re-run after it gets merged.

Fix no-async-fn-without-await when used with default parser (fixes #147)

---

index.js
package.json

Probably a reason you haven't done it yet (other than the fact it's a breaking change), but it's annoying having ava override our setting just because we want to use recommended config, which means we have to specify `ecmaVersion` multiple places (as we only have ava in test dirs)
An idea might be to drop the version entirely from recommended? That's still breaking, though.
Could do `require('eslint/package.json').version` and check if it's new enough to keep it non-breaking?

Set `ecmaVersion` to `2017`

---

rules/no-async-fn-without-await.js
test/no-async-fn-without-await.js

Fixes #160: Fixes `no-async-without-fn` not reporting anything when not using a title.
I decided to simply check if any of the first two arguments is a async. I thought about writing a function that finds the implementation function among the arguments, but that can be rather tricky when using identifiers.
```js
function implementationFn(t, argFunction) {
t.throws(argFunction(1));
}
implementationFn.title = 'foo'
test(implementationFn, async n => {}); // We'd probably assume the second function is the implementation function, but no.
```
This could create false positives in the case shown above, if that function also does not contain `async`. Sounds like an extreme edge case, and they should not mark it as async anyway IMO, so it should be fine.

Fix `no-async-without-fn` when using a title

---

rules/assertion-arguments.js
test/assertion-arguments.js

Allow passing an argument to `t.end()` (fixes #164)
`t.end()` is now a special case for this rule, as the optional argument it allows is not a message that we'd like to enforce based on the `message` option.
I've simplified the implementation a bit by re-using `util.getMembers`.

Allow passing an argument to `t.end()` (fixes #164)

---

rules/assertion-arguments.js
test/assertion-arguments.js
test/no-duplicate-modifiers.js
test/no-unknown-modifiers.js
test/use-t-well.js
util.js

Fixes #169: Support `t.snapshot()`
I also added a commit to remove the use of `...` object assign operator as it's not supported out of the box in AVA 0.18 anymore.

Support t.snapshot()

---

rules/no-identical-title.js
test/no-identical-title.js

Fixes #168, no-identical-title: Do not report identical titles when using macros
cc @novemberborn

(#168) no-identical-title: Do not report identical titles when using macros

---

create-ava-rule.js
rules/no-async-fn-without-await.js
rules/no-cb-test.js
rules/no-duplicate-modifiers.js
rules/no-identical-title.js
rules/no-only-test.js
rules/no-skip-test.js
rules/no-unknown-modifiers.js
test/no-async-fn-without-await.js
test/no-cb-test.js
test/no-duplicate-modifiers.js
test/no-identical-title.js
test/no-only-test.js
test/no-skip-test.js
test/no-unknown-modifiers.js
util.js

Hi all! It's been a while :sweat_smile: 
I've been increasingly growing annoyed by some error reports that I have in my IDE while developping.
One of the most annoying ones is using `test.only`, which targets the whole test call (in IDEs, it puts puts squiggly lines under the targeted code, as in the screenshot below), which makes it hard to notice other ESLint errors.
I started working on this and though that the other rules were easy to fix too, so I just did all those that I could think of. Let me know if you prefer that I split this into multiple PRs.
List of changes:
- no-only-test: Now targets the `only` property instead of the whole test call
- no-skip-test: Now targets the `skip` property instead of the whole test call
- no-unknown-modifiers: Now targets the unknown properties …

Improve target reporting

---

rules/assertion-arguments.js
rules/assertion-message.js
rules/max-asserts.js
rules/no-async-fn-without-await.js
rules/no-cb-test.js
rules/no-duplicate-modifiers.js
rules/no-identical-title.js
rules/no-ignored-test-files.js
rules/no-invalid-end.js
rules/no-nested-tests.js
rules/no-only-test.js
rules/no-skip-assert.js
rules/no-skip-test.js
rules/no-statement-after-end.js
rules/no-todo-implementation.js
rules/no-todo-test.js
rules/no-unknown-modifiers.js
rules/prefer-async-await.js
rules/prefer-power-assert.js
rules/test-ended.js
rules/test-title.js
rules/use-t-well.js
rules/use-t.js
rules/use-test.js
rules/use-true-false.js
test/util.js
util.js

ESLint v4.15.0 added an official location for rules to store a URL to their documentation in the rule metadata in eslint/eslint#9788. This adds the URL to all the existing rules so anything consuming them can
know where their documentation is without having to resort to external packages to guess.

Add URL to rule documentation to the metadata

---

rules/assertion-arguments.js
rules/assertion-message.js
rules/max-asserts.js
rules/no-async-fn-without-await.js
rules/no-cb-test.js
rules/no-duplicate-modifiers.js
rules/no-identical-title.js
rules/no-ignored-test-files.js
rules/no-invalid-end.js
rules/no-nested-tests.js
rules/no-only-test.js
rules/no-skip-assert.js
rules/no-skip-test.js
rules/no-statement-after-end.js
rules/no-todo-implementation.js
rules/no-todo-test.js
rules/no-unknown-modifiers.js
rules/prefer-async-await.js
rules/prefer-power-assert.js
rules/test-ended.js
rules/test-title.js
rules/use-t-well.js
rules/use-t.js
rules/use-test.js
rules/use-true-false.js
test/util.js
util.js

`module.parent` is cached after the first `require` and this results in nearly all rules having the URL to `assertion-arguments`. Here's a simple repro:
```js
'use strict';
const { rules } = require('eslint-plugin-ava');
const wrongLinks = [];
for (const ruleName of Object.keys(rules)) {
const rule = rules[ruleName];
const { url } = rule.meta.docs;
if (!url.includes(ruleName)) wrongLinks.push(ruleName);
}
console.log(wrongLinks);
```
```
λ node rule-docs-url.js
[ 'max-asserts',
'no-async-fn-without-await',
'no-cb-test',
'no-duplicate-modifiers',
'no-identical-title',
'no-ignored-test-files',
'no-invalid-end',
'no-nested-tests',
'no-only-test',
'no-skip-assert',
'no-skip-test',
'no-statement-after-end',
'no-todo-implementation',
'no-todo-test',
'no-unknown-modifiers',
'prefer-async-await', …
```

Do not use module.parent for resolving rule name

---

rules/use-t.js
test/use-t.js

As mentioned in #127, calls to test using macros would treat any function arguments to the macro as needing to meet the requirements of the use-t validation.
This change will evaluate functions for the "t" parameter only if the function is the first or second position of the call to test.
Fixes #127

Fix `use-t` failing on macros

---

docs/rules/no-import-test-files.md
index.js
readme.md
rules/no-ignored-test-files.js
rules/no-import-test-files.js
test/no-ignored-test-files-with-package.js
test/no-import-test-files.js
util.js

Fixes #141 
Created a rule that forbids test files in any form.

Add `no-import-test-file` rule

---

package.json
util.js

This ensures user settings don't leak into our use of esm.

Upgrade esm and use force option

---

docs/rules/use-t-well.md
rules/use-t-well.js
test/use-t-well.js

Allow the use of `t.title` with the `use-t-well` rule

---

rules/test-ended.js
test/test-ended.js

Calling a `.cb` test with the first argument being a reference disables the rule

---

rules/assertion-arguments.js
rules/assertion-message.js
rules/max-asserts.js
rules/no-invalid-end.js
rules/no-skip-assert.js
rules/use-t-well.js
rules/use-true-false.js
test/assertion-arguments.js
test/max-asserts.js
test/no-invalid-end.js
test/no-skip-assert.js
test/use-t-well.js
test/use-true-false.js
util.js

Add tests for all rules using "nameOfRootObject"
Fix #223

Prevent incorrect detection of AVA functions when accessing through "context"

---

rules/no-import-test-files.js
test/no-import-test-files.js

Fix `no-import-test-files` rule incorrectly reporting module names ending in `.js`

---

docs/rules/test-title.md
rules/test-title.js
test/test-title.js

Remove options from the `test-title` rule

---

docs/rules/use-t-well.md
readme.md
rules/use-t-well.js
test/use-t-well.js

Add auto-fix of misspelled `falsey` to `falsy`

---

rules/prefer-t-regex.js
test/prefer-t-regex.js

Secure function call without property on prefer-t-regex

---

rules/no-import-test-files.js
test/no-import-test-files.js

Only attempt to classify imports that are file paths. Fixes #253.

Ensure @scoped-packages are ignored in no-import-test-files

---

docs/rules/no-ignored-test-files.md
docs/rules/no-import-test-files.md
rules/no-ignored-test-files.js
rules/no-import-test-files.js
util.js

Fixes #252.
Depends on https://github.com/avajs/ava/pull/2150.

Support extensions, files and helpers in `no-ignored-test-files` and `no-import-test-files` rules

---

rules/assertion-arguments.js
rules/max-asserts.js
rules/test-title-format.js

Fixes #214.
Honestly, I'm not sure this issue makes a lot of sense. There were only three rules I saw that had options at all:
* `assertion-arguments`: Default is `undefined`. I added it explicitly but it seems kind of redundant.
* `max-asserts`: Cannot use a default as per https://github.com/avajs/eslint-plugin-ava/issues/214#issuecomment-478915717. I'm not a big fan of non-object options anyway. I recommend converting from the numeric option to an object which would then pick up the default. This would be a breaking change, though. Alternatively, set the default in `schema` but also use the fallback in `create`.
* `test-title-format`: Default is also `undefined`.
Am I missing something about this request? There was no `Object.assign` usage to replace.

Add defaults to schema

---

rules/no-nested-tests.js
rules/test-title-format.js
test/no-nested-tests.js

I've done a grep and it turns out these two rules have missing period in the report message. Now I add them for consistency.

Add missing period in some rule messages

---

docs/rules/no-inline-assertions.md
index.js
readme.md
rules/no-inline-assertions.js
test/no-inline-assertions.js

Update (2019-06-13): I have pushed `no-inline-assertions` rule implementation, see the docs and test cases. This rule will fail
Any `MemberExpression` as the arrow function body
```js
test('foo', t => t.true(fn()));
test('foo', t => t.skip());
test('foo', t => 
t.true(fn())
);
// ...
```
And any `BlockStatement` within the same line
```js
test('foo', t => { t.true(fn()) });
test('foo', t => { t.skip() });
```
---
(2019-06-12)
This is an early-stage design discussion, as I have the following question regards to this rule. I would also put up my thoughts and any community input is welcome.
The `no-inline-assertions` was originally proposed at #152, where Sindre listed two example
```js
test('foo', t => t.true(fn()));
```
```js
test('foo', t => {
t.true(fn());
});
```
While the example above …

Add `no-inline-assertions` rule

---

docs/rules/no-incorrect-deep-equal.md
index.js
readme.md
rules/no-incorrect-deep-equal.js
test/no-incorrect-deep-equal.js

Closes #158.
Does not cover `t.deepEqual(1, expression); // ?` situations. Does not fix back to `deepEqual` if it detects a non-literal in `is` -- I felt that would be an ambiguous situation in the event that someone actually wanted to compare by reference.

Add `no-incorrect-deep-equal` rule

---

create-ava-rule.js
test/create-ava-rule.js

Support named imports and destructured requires

---

docs/rules/test-title-format.md

The examples incorrect enabled the `test-title` rule instead of the `test-title-format` rule

docs: fix examples for `test-title-format`

---

docs/rules/no-ignored-test-files.md
rules/no-ignored-test-files.js
test/no-ignored-test-files.js
test/no-import-test-files.js

This is being removed from AVA 3, see https://github.com/avajs/ava/pull/2323.

Remove handling of isSource classification

---

docs/rules/assertion-arguments.md
docs/rules/hooks-order.md
docs/rules/max-asserts.md
docs/rules/no-async-fn-without-await.md
docs/rules/no-cb-test.md
docs/rules/no-duplicate-modifiers.md
docs/rules/no-identical-title.md
docs/rules/no-ignored-test-files.md
docs/rules/no-import-test-files.md
docs/rules/no-inline-assertions.md
docs/rules/no-invalid-end.md
docs/rules/no-nested-tests.md
docs/rules/no-only-test.md
docs/rules/no-skip-assert.md
docs/rules/no-skip-test.md
docs/rules/no-statement-after-end.md
docs/rules/no-todo-implementation.md
docs/rules/no-todo-test.md
docs/rules/no-unknown-modifiers.md
docs/rules/prefer-async-await.md
docs/rules/prefer-power-assert.md
docs/rules/prefer-t-regex.md
docs/rules/test-ended.md
docs/rules/test-title-format.md
docs/rules/test-title.md
docs/rules/use-t-well.md
docs/rules/use-t.md
docs/rules/use-test.md
docs/rules/use-true-false.md

Out of the box, ESM syntax will only work in Node.js 13, so having that
as the default example is misleading.

Use CJS syntax in documentation

---

docs/rules/use-test.md
rules/use-test.js
test/use-test.js

Fix #293 
Change `use-test` to allow importing AVA as `anyTest` in order to account for the example in [Typing t.context](https://github.com/avajs/ava/blob/master/docs/recipes/typescript.md#typing-tcontext).
This change could be further improved by making sure that when AVA is imported as `any` it is assigned to a variable name `test`, e.g:
```
const test = anyTest as TestInterface<{foo: string}>;
```
In other words the following should be invalid:
```
import anyTest, {TestInterface} from 'ava';
const myTest = anyTest as TestInterface<{foo: string}>;
```
That's important because some other rules depends on the AVA object to be named `test`. However, the change in that PR is still better than forcing users to disable the rules.
Implementing such validation is beyond my knowledge of ESLint …

Allow importing AVA as `anyTest` in TypeScript files

---

rules/assertion-arguments.js
test/assertion-arguments.js

Updating the eslint plugin to support the new `t.timeout(ms, message?)` custom assertion message as described by https://github.com/avajs/ava/pull/2524.
Tried to update existing tests to accommodate existing tests with similar conditions, but please let me know If additional work is required.

Support assertion message in `t.timeout()

---

rules/no-statement-after-end.js
test/no-statement-after-end.js

Fixes #315 by changing the way `no-statement-after-end` records `CodePathSegment`s. The stack is used only to hold the in-progress segment in the outer `CodePath`s. When `CodePath`s begin or end, the current segment is pushed onto or popped from the stack. When `CodePathSegment`s begin or end, the current segment is set or unset.
When in unreachable code at the end of a path, the current segment is therefore undefined, rather than erroneously taken from the next-outermost path.
Checks whether the current segment is set before operating on it.
(Interestingly, this rule doesn't catch statements after `t.end()` in unreachable code, e.g.:
```javascript
throw new Error();
t.end();
1; // <-- does not trigger a report
```
This behavior predates this PR.)
While I believe this fixes the issue, I …

Fix crash, false-positive in no-statement-after-end

---

docs/rules/assertion-arguments.md
rules/assertion-arguments.js
test/assertion-arguments.js

This will check for the presence of the extra argument (which should be the `message`) and verify if it's a string.
It will try to lookup variable and its value in the scope, but non-linear flow could break it.
```js
let message;
function woops () {
message = null;
}
message = 'ok';
woops();
t.is('same', 'same', message); // <= this will not raise an error
```
Should we cover this ?
Fixes #167
---
<details>
<summary>
<b>IssueHunt Summary</b>
</summary>
This pull request has been submitted to:
- [#167: The `assertion-arguments` rule should validate message argument type](https://issuehunt.io/repos/49722492/issues/167)
---
</details>

Ensure the assertion message is a string

---

rules/prefer-t-regex.js
test/prefer-t-regex.js

This pull request is a continuation from #297 work and fixes #275 
I've added support for `RegExp()` as requested in the previous PR as well as the necessary tests. 🦄
---
<details>
<summary>
<b>IssueHunt Summary</b>
</summary>
This pull request has been submitted to:
- [#275: Detect more assertions in the `t-prefer-regex` rule](https://issuehunt.io/repos/49722492/issues/275)
---
</details>

Detect more assertions in `prefer-t-regex`

---

rules/no-todo-test.js

I just noticed that there's an extra "be" in the message the rule `no-todo-test` reports.

Fix small typo in rule report message of no-todo-test

---

docs/rules/no-only-test.md
docs/rules/no-skip-test.md
readme.md
rules/no-only-test.js
rules/no-skip-test.js
test/no-only-test.js
test/no-skip-test.js

Closes https://github.com/avajs/eslint-plugin-ava/pull/324
https://github.com/avajs/eslint-plugin-ava/issues/281#issuecomment-587137623

Use suggestions API for `no-only-test` and `no-skip-test`

---

docs/rules/use-test.md
package.json
rules/use-test.js
test/use-test.js

This fixes #320 by ignoring type-only imports (like `import type { Macro } from 'ava';`).

`use-test`: Ignore type import

---

docs/rules/assertion-arguments.md
docs/rules/hooks-order.md
docs/rules/max-asserts.md
docs/rules/no-async-fn-without-await.md
docs/rules/no-duplicate-modifiers.md
docs/rules/no-identical-title.md
docs/rules/no-ignored-test-files.md
docs/rules/no-import-test-files.md
docs/rules/no-incorrect-deep-equal.md
docs/rules/no-inline-assertions.md
docs/rules/no-nested-tests.md
docs/rules/no-only-test.md
docs/rules/no-skip-assert.md
docs/rules/no-skip-test.md
docs/rules/no-todo-implementation.md
docs/rules/no-todo-test.md
docs/rules/no-unknown-modifiers.md
docs/rules/prefer-async-await.md
docs/rules/prefer-power-assert.md
docs/rules/prefer-t-regex.md
docs/rules/test-title-format.md
docs/rules/test-title.md
docs/rules/use-t-throws-async-well.md
docs/rules/use-t-well.md
docs/rules/use-t.md
docs/rules/use-test.md
docs/rules/use-true-false.md
package.json
readme.md

First stable [v1.0.0](https://github.com/bmish/eslint-doc-generator/releases/tag/v1.0.0) release of [eslint-doc-generator](https://github.com/bmish/eslint-doc-generator).
Originally added in:
* https://github.com/avajs/eslint-plugin-ava/pull/348
I ran `npm run update:eslint-docs` to update the docs.

Update to eslint-doc-generator v1.0.0

---

rules/prefer-t-regex.js
test/prefer-t-regex.js

fixes some of the prefer-t-regex issues. #346 #347

fix: guard against type errors in prefer-t-regex
